In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
import os

In [4]:
# df1 = pd.read_csv('emp2022.csv')
df1 = pd.read_excel('/content/drive/MyDrive/KDT/파이널프로젝트/2019_직원 데이터.xlsx')

In [5]:
df1 = df1.loc[:, ['corp_code','corp_name','sexdstn','rgllbr_co','sm','avrg_cnwk_sdytrn','jan_salary_am']]
# df2 = df2.loc[:, ['corp_code','corp_name','sexdstn','rgllbr_co','sm','avrg_cnwk_sdytrn','jan_salary_am']]

In [6]:
df1

,corp_code,corp_name,sexdstn,rgllbr_co,sm,avrg_cnwk_sdytrn,jan_salary_am
0,956028,엑세스바이오,남,12,12,3.36,"72,084"
1,956028,엑세스바이오,여,8,8,3.81,"49,398"
2,956028,엑세스바이오,남,4,4,4.18,"77,087"
3,956028,엑세스바이오,여,-,-,-,-
4,956028,엑세스바이오,남,7,7,3.67,"88,461"
...,...,...,...,...,...,...,...
7842,305668,새론오토모티브,여,2,11,11,"46,839,000"
7843,259545,엠에스오토텍,남,208,232,10년 3개월,"62,000,000"
7844,259545,엠에스오토텍,여,9,11,11년 11개월,"38,000,000"
7845,458234,아시아나IDT,남,337,504,8.2,"64,000,000"
7846,458234,아시아나IDT,여,99,108,9.4,"59,000,000"

In [7]:
# 이상값 대체
df1.replace('-', '', regex =True, inplace=True)
df1.replace('--', '', regex =True, inplace=True)
df1.replace(',', '', regex =True, inplace=True)

# object타입을 float타입으로 변환
df1['rgllbr_co'] = pd.to_numeric(df1['rgllbr_co'])
df1['sm'] = pd.to_numeric(df1['sm'])
df1['jan_salary_am'] = pd.to_numeric(df1['jan_salary_am'])

# 결측치 모두 0값으로 대체
df1.fillna(0, inplace = True)

# 결과 확인
df1.info()

df1.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7847 entries, 0 to 7846
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   corp_code         7847 non-null   int64
 1   corp_name         7847 non-null   object
 2   sexdstn           7847 non-null   object
 3   rgllbr_co         7847 non-null   float64
 4   sm                7847 non-null   float64
 5   avrg_cnwk_sdytrn  7847 non-null   object
 6   jan_salary_am     7847 non-null   float64
dtypes: float64(3), int64(1), object(3)
memory usage: 429.3+ KB

corp_code           0
corp_name           0
sexdstn             0
rgllbr_co           0
sm                  0
avrg_cnwk_sdytrn    0
jan_salary_am       0
dtype: int64

In [8]:
# avrg_cnwk_sdytrn 제거
df1.drop(columns=['avrg_cnwk_sdytrn'], inplace=True)

# 결과 확인
print(df1)

      corp_code corp_name sexdstn  rgllbr_co     sm  jan_salary_am
0        956028    엑세스바이오       남       12.0   12.0        72084.0
1        956028    엑세스바이오       여        8.0    8.0        49398.0
2        956028    엑세스바이오       남        4.0    4.0        77087.0
3        956028    엑세스바이오       여        0.0    0.0            0.0
4        956028    엑세스바이오       남        7.0    7.0        88461.0
...         ...       ...     ...        ...    ...            ...
7842     305668   새론오토모티브       여        2.0   11.0     46839000.0
7843     259545    엠에스오토텍       남      208.0  232.0     62000000.0
7844     259545    엠에스오토텍       여        9.0   11.0     38000000.0
7845     458234   아시아나IDT       남      337.0  504.0     64000000.0
7846     458234   아시아나IDT       여       99.0  108.0     59000000.0

[7847 rows x 6 columns]

In [9]:
# df1 저장
df1.to_csv('df1.csv', index=False)

In [10]:
# 성별(sexdstn), 회사 코드(corp_code), 회사 이름(corp_name)별로 합계 계산
result = df1.groupby(['corp_code', 'corp_name', 'sexdstn']).agg({
    'rgllbr_co': 'sum',
    'sm': 'sum',
    'jan_salary_am': 'sum'
}).reset_index()

print(result)

      corp_code      corp_name sexdstn  rgllbr_co     sm  jan_salary_am
0        100258           에스마크       남       10.0   10.0   5.399600e+10
1        100601          강원에너지       남       92.0  100.0   6.370000e+06
2        100601          강원에너지       여        6.0    7.0   6.166000e+06
3        100939         강남제비스코       남      586.0  643.0   5.433600e+07
4        100939         강남제비스코       여       42.0   46.0   4.005100e+07
...         ...            ...     ...        ...    ...            ...
4736    1416642           다보링크       남        0.0    0.0   0.000000e+00
4737    1416642           다보링크       여        0.0    0.0   0.000000e+00
4738    1418543  케이비제20호기업인수목적       남        1.0    1.0   2.400000e+07
4739    1419135            이노진       남       32.0   32.0   3.182040e+07
4740    1419135            이노진       여       25.0   25.0   2.094520e+07

[4741 rows x 6 columns]

In [11]:
df = result.iloc[:,1:].copy()
df

          corp_name sexdstn  rgllbr_co     sm  jan_salary_am
0              에스마크       남       10.0   10.0   5.399600e+10
1             강원에너지       남       92.0  100.0   6.370000e+06
2             강원에너지       여        6.0    7.0   6.166000e+06
3            강남제비스코       남      586.0  643.0   5.433600e+07
4            강남제비스코       여       42.0   46.0   4.005100e+07
...             ...     ...        ...    ...            ...
4736           다보링크       남        0.0    0.0   0.000000e+00
4737           다보링크       여        0.0    0.0   0.000000e+00
4738  케이비제20호기업인수목적       남        1.0    1.0   2.400000e+07
4739            이노진       남       32.0   32.0   3.182040e+07
4740            이노진       여       25.0   25.0   2.094520e+07

[4741 rows x 5 columns]

In [12]:
# pivot_table을 사용하여 회사별로 성별을 열로 변환
df_pivot = df.pivot_table(index='corp_name', columns='sexdstn', values=['rgllbr_co', 'sm', 'jan_salary_am'], aggfunc='sum')

# 열 이름 정리
df_pivot.columns = [f'{col}_{sexdstn.lower()}' for col, sexdstn in df_pivot.columns]

df_pivot['total_emp'] = df_pivot['sm_남'] + df_pivot['sm_여']
df_pivot.fillna(0, inplace= True)
df_pivot.isnull().sum()
df_pivot

,jan_salary_am_남,jan_salary_am_여,rgllbr_co_남,rgllbr_co_여,sm_남,sm_여,total_emp
corp_name,,,,,,,
3S,54908000.0,32588000.0,59.0,9.0,59.0,9.0,68.0
AJ네트웍스,159765000.0,74281000.0,335.0,178.0,345.0,186.0,531.0
AK홀딩스,69000000.0,50000000.0,15.0,4.0,16.0,4.0,20.0
APS,58016000.0,29407000.0,54.0,11.0,54.0,11.0,65.0
AP시스템,54333000.0,33936000.0,444.0,25.0,445.0,36.0,481.0
...,...,...,...,...,...,...,...
흥국에프엔비,40036000.0,24580000.0,101.0,54.0,101.0,58.0,159.0
흥국화재,81798000.0,47007000.0,624.0,487.0,651.0,574.0,1225.0
흥아해운,128918000.0,36248000.0,193.0,6.0,333.0,6.0,339.0
희림,255000000.0,161000000.0,983.0,223.0,989.0,226.0,1215.0
힘스,245624000.0,187529000.0,205.0,21.0,207.0,22.0,229.0

In [13]:
# women_ratio 추가
df_pivot['women_ratio'] = df_pivot['sm_여'] / (df_pivot['total_emp']) * 100

# man_ratio 추가
df_pivot['man_ratio'] = df_pivot['sm_남'] / (df_pivot['total_emp']) * 100

# Full-time employee ratio 추가 (남)
df_pivot['Full-time employee ratio_남'] = df_pivot['rgllbr_co_남'] / df_pivot['sm_남']

# Full-time employee ratio 추가 (여)
df_pivot['Full-time employee ratio_여'] = df_pivot['rgllbr_co_여'] / df_pivot['sm_여']

In [14]:
result = df_pivot.copy()
result

,jan_salary_am_남,jan_salary_am_여,rgllbr_co_남,rgllbr_co_여,sm_남,sm_여,total_emp,women_ratio,man_ratio,Full-time employee ratio_남,Full-time employee ratio_여
corp_name,,,,,,,,,,,
3S,54908000.0,32588000.0,59.0,9.0,59.0,9.0,68.0,13.235294,86.764706,1.000000,1.000000
AJ네트웍스,159765000.0,74281000.0,335.0,178.0,345.0,186.0,531.0,35.028249,64.971751,0.971014,0.956989
AK홀딩스,69000000.0,50000000.0,15.0,4.0,16.0,4.0,20.0,20.000000,80.000000,0.937500,1.000000
APS,58016000.0,29407000.0,54.0,11.0,54.0,11.0,65.0,16.923077,83.076923,1.000000,1.000000
AP시스템,54333000.0,33936000.0,444.0,25.0,445.0,36.0,481.0,7.484407,92.515593,0.997753,0.694444
...,...,...,...,...,...,...,...,...,...,...,...
흥국에프엔비,40036000.0,24580000.0,101.0,54.0,101.0,58.0,159.0,36.477987,63.522013,1.000000,0.931034
흥국화재,81798000.0,47007000.0,624.0,487.0,651.0,574.0,1225.0,46.857143,53.142857,0.958525,0.848432
흥아해운,128918000.0,36248000.0,193.0,6.0,333.0,6.0,339.0,1.769912,98.230088,0.579580,1.000000
희림,255000000.0,161000000.0,983.0,223.0,989.0,226.0,1215.0,18.600823,81.399177,0.993933,0.986726
힘스,245624000.0,187529000.0,205.0,21.0,207.0,22.0,229.0,9.606987,90.393013,0.990338,0.954545

In [15]:
result.to_csv('emp2019.csv')